[tox]
envlist =
    py37
    py38
    py39
    py310
    py311
    py312
    py313
    pypy38
    pypy39
    pypy310
    pypy311
    flake8
requires =
    tox-uv

[testenv]
runner = uv-venv-lock-runner
setenv =
    PYTHONPATH = {toxinidir}
commands = django-admin test --settings=tests.settings -v 2

[testenv:flake8]
dependency_groups = pep8
commands = flake8 django_datadog_logger tests
